#!/bin/bash
# Guía rápida de ejecución - Smart Locker Camera System

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║         SMART LOCKER - SISTEMA DE RECONOCIMIENTO FACIAL      ║"
echo "║                 Raspberry Pi 5 - Completamente Funcional      ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}VERIFICACIÓN PREVIA:${NC}"
echo "✓ Cámara: OV5647 conectada y funcional"
echo "✓ Libcamera: v0.7.0 instalado"
echo "✓ Picamera2: disponible en Python"
echo "✓ Video feed: Implementado y funcionando"
echo ""

echo -e "${BLUE}FORMAS DE EJECUTAR:${NC}"
echo ""
echo "1️⃣  MÉTODO RECOMENDADO (Sistema Python):"
echo -e "${GREEN}   /usr/bin/python3 main.py --mode locker${NC}"
echo ""
echo "2️⃣  MÉTODO CON SCRIPT:"
echo -e "${GREEN}   chmod +x run.sh${NC}"
echo -e "${GREEN}   ./run.sh --mode locker${NC}"
echo ""
echo "3️⃣  MODO ADMINISTRACIÓN:"
echo -e "${GREEN}   /usr/bin/python3 main.py --mode admin${NC}"
echo ""

echo -e "${BLUE}QUÉ VERÁS:${NC}"
echo ""
echo "📱 Pantalla Standby:"
echo "   🔒 Smart Locker"
echo "   'Acerca tu rostro a la cámara'"
echo "   ● ● ● (animado)"
echo "   [DEV] Iniciar escaneo"
echo ""
echo "📷 Pantalla Scanning (click en botón):"
echo "   TU ROSTRO EN VIVO (video feed)"
echo "   ✓ Rectángulos verdes = rostros detectados"
echo "   Estado: 'Posiciona tu rostro...'"
echo "   Intentos: 0 / 3"
echo ""
echo "✅ Pantalla Success:"
echo "   ✓ Acceso concedido"
echo "   Tu Nombre"
echo "   Casillero #42"
echo "   (8 segundos después vuelve a standby)"
echo ""

echo -e "${BLUE}CARACTERÍSTICAS IMPLEMENTADAS:${NC}"
echo "✅ Captura de vídeo en tiempo real (picamera2)"
echo "✅ Detección de rostros (OpenCV DNN)"
echo "✅ Feed de vídeo en la pantalla física"
echo "✅ Threading para no bloquear UI"
echo "✅ Navegación sincronizada entre pantallas"
echo "✅ Rectángulos verdes alrededor de rostros"
echo "✅ Sistema de intentos"
echo "✅ Timeouts automáticos"
echo "✅ Logging detallado"
echo ""

echo -e "${BLUE}DOCUMENTACIÓN:${NC}"
echo "📚 QUICKSTART.md              → Inicio rápido"
echo "📚 SETUP_GUIDE.md            → Guía completa de instalación"
echo "📚 VIDEO_FEED_EXPLANATION.md → Cómo funciona el video feed"
echo "📚 SOLUTION_SUMMARY.md       → Resumen técnico completo"
echo ""

echo -e "${BLUE}DIAGNÓSTICO:${NC}"
echo -e "${GREEN}   python3 diagnose_camera.py${NC}"
echo ""

echo -e "${BLUE}LOGS EN TIEMPO REAL:${NC}"
echo -e "${GREEN}   tail -f logs/locker_system.log${NC}"
echo -e "${GREEN}   LOG_LEVEL=DEBUG /usr/bin/python3 main.py --mode locker${NC}"
echo ""

echo -e "${YELLOW}¿PRIMERA VEZ?${NC}"
echo "1. Lee: QUICKSTART.md"
echo "2. Ejecuta: /usr/bin/python3 main.py --mode locker"
echo "3. Click en [DEV] Iniciar escaneo"
echo "4. ¡Deberías ver tu rostro en la pantalla!"
echo ""

echo -e "${GREEN}═══════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}        ¡LISTO PARA USAR! 🚀${NC}"
echo -e "${GREEN}═══════════════════════════════════════════════════════════${NC}"
echo ""
